version: '3.9'

services:
  app:
    container_name: app_insect
    build: .
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    external_links:
      - postgres
    networks:
      - cloud

  postgres:
    image: postgres:14
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - cloud

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - cloud
volumes:
  api:
  db:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  cloud:
    driver: bridge